name: gallery
description: Gallery project to showcase app_ui
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_ui:
    path: ../
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true

